# Generated by Django 2.0.2 on 2018-05-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectionalignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='user_session_key',
            field=models.CharField(default='', max_length=64),
        ),
    ]
