# Generated by Django 2.0.2 on 2018-02-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('jp', 'Japanese'), ('ru', 'Russian')], db_index=True, max_length=8)),
                ('ranking', models.PositiveIntegerField(db_index=True)),
                ('translation', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('title', 'language')},
        ),
    ]
