"""
Django settings for gapfindertools project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from gapfindertools.settings_base import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    '#)zbti_w!for_jack0xpefbi=&c@tsb2oua4j$e!djyhy&x9g7'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['gapfinder-tools.wmflabs.org']

WSGI_APPLICATION = 'gapfindertools.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         # https://wikitech.wikimedia.org/wiki/Help:Toolforge/Database#User_databases
#         'HOST': 'tools.db.svc.eqiad.wmflabs',
#         'NAME': 'u10570_gapfindertools',
#         'OPTIONS': {
#            'read_default_file': '/etc/replica.my.cnf'
#          }
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'data/db.sqlite3')
    }
}
