# Generated by Django 2.0.2 on 2018-02-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_username', models.CharField(max_length=255, verbose_name='Wiki username')),
                ('ar_proficiency', models.CharField(blank=True, choices=[('0', "0 - If you don't understand the language at all."), ('1', '1 - Basic ability - enough to understand written material or simple questions in this language.'), ('2', '2 - Intermediate ability - enough for editing or discussions.'), ('3', '3 - Advanced level - though you can write in this language with no problem, some small errors might occur.'), ('4', "4 - Near-native level—although it's not your first language from birth, your ability is something like that of a native speaker."), ('5', '5 - Professional proficiency.'), ('N', 'N - Native speakers who use a language every day and have a thorough grasp of it, including colloquialisms and idioms.')], max_length=1)),
                ('en_proficiency', models.CharField(blank=True, choices=[('0', "0 - If you don't understand the language at all."), ('1', '1 - Basic ability - enough to understand written material or simple questions in this language.'), ('2', '2 - Intermediate ability - enough for editing or discussions.'), ('3', '3 - Advanced level - though you can write in this language with no problem, some small errors might occur.'), ('4', "4 - Near-native level—although it's not your first language from birth, your ability is something like that of a native speaker."), ('5', '5 - Professional proficiency.'), ('N', 'N - Native speakers who use a language every day and have a thorough grasp of it, including colloquialisms and idioms.')], max_length=1)),
                ('es_proficiency', models.CharField(blank=True, choices=[('0', "0 - If you don't understand the language at all."), ('1', '1 - Basic ability - enough to understand written material or simple questions in this language.'), ('2', '2 - Intermediate ability - enough for editing or discussions.'), ('3', '3 - Advanced level - though you can write in this language with no problem, some small errors might occur.'), ('4', "4 - Near-native level—although it's not your first language from birth, your ability is something like that of a native speaker."), ('5', '5 - Professional proficiency.'), ('N', 'N - Native speakers who use a language every day and have a thorough grasp of it, including colloquialisms and idioms.')], max_length=1)),
                ('fr_proficiency', models.CharField(blank=True, choices=[('0', "0 - If you don't understand the language at all."), ('1', '1 - Basic ability - enough to understand written material or simple questions in this language.'), ('2', '2 - Intermediate ability - enough for editing or discussions.'), ('3', '3 - Advanced level - though you can write in this language with no problem, some small errors might occur.'), ('4', "4 - Near-native level—although it's not your first language from birth, your ability is something like that of a native speaker."), ('5', '5 - Professional proficiency.'), ('N', 'N - Native speakers who use a language every day and have a thorough grasp of it, including colloquialisms and idioms.')], max_length=1)),
                ('ja_proficiency', models.CharField(blank=True, choices=[('0', "0 - If you don't understand the language at all."), ('1', '1 - Basic ability - enough to understand written material or simple questions in this language.'), ('2', '2 - Intermediate ability - enough for editing or discussions.'), ('3', '3 - Advanced level - though you can write in this language with no problem, some small errors might occur.'), ('4', "4 - Near-native level—although it's not your first language from birth, your ability is something like that of a native speaker."), ('5', '5 - Professional proficiency.'), ('N', 'N - Native speakers who use a language every day and have a thorough grasp of it, including colloquialisms and idioms.')], max_length=1)),
                ('ru_proficiency', models.CharField(blank=True, choices=[('0', "0 - If you don't understand the language at all."), ('1', '1 - Basic ability - enough to understand written material or simple questions in this language.'), ('2', '2 - Intermediate ability - enough for editing or discussions.'), ('3', '3 - Advanced level - though you can write in this language with no problem, some small errors might occur.'), ('4', "4 - Near-native level—although it's not your first language from birth, your ability is something like that of a native speaker."), ('5', '5 - Professional proficiency.'), ('N', 'N - Native speakers who use a language every day and have a thorough grasp of it, including colloquialisms and idioms.')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.TextField(verbose_name='Section title in source language')),
                ('source_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ja', 'Japanese'), ('ru', 'Russian')], db_index=True, max_length=8, verbose_name='Section source language')),
                ('source_rank', models.PositiveIntegerField(db_index=True, verbose_name='Section rank in source language')),
                ('target_titles', models.TextField(verbose_name='List of section titles in target language')),
                ('target_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ja', 'Japanese'), ('ru', 'Russian')], db_index=True, max_length=8, verbose_name='Section target language')),
                ('map_count', models.PositiveSmallIntegerField(default=0, verbose_name='Number of times this entry has been mapped')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('source_title', 'source_language')},
        ),
    ]
