# Generated by Django 2.0.2 on 2018-02-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectionmapping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionmapping',
            name='source_rank',
        ),
        migrations.AddField(
            model_name='section',
            name='source_rank',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Section rank in source language'),
            preserve_default=False,
        ),
    ]
